### ISSUE TITLE
Previews also in the browse dialog?

### ISSUE THREAD

**Issue by morphix9** [kareldonk/WMFPreview#1]
The previews are working perfect in File Explorer, but not in the browse dialog. Is this just me? Is this possible to be fixed?

Thanks for your work and sharing the extension for free!

**Comment by kareldonk** [comment]
Can you provide more details? What version of Windows are you using and what platform (32-bit or 64bit)? And from what application are you opening the browse dialog? Some applications are using their own browse dialog and not the standard dialogs provided by the OS. In that case you may not see previews.

**Comment by morphix9** [comment]
Thanks for your fast response.
Using Windows 10 and MS PowerPoint 2016 (browse dialog inside PowerPoint when inserting a Picture (EMF).

**Comment by kareldonk** [comment]
Ah yes, with the MS Office applications this is a known issue. For example, you will also not see the previews when you view an email with WMF/EMF attachments in Outlook. I haven't yet been able to spend enough time on this. I had contacted Microsoft's developers but they were also not able to provide any answers as to why that was happening. It's on my to-do list to investigate as I find time.

**Comment by morphix9** [comment]
Thanks!

**Comment by kareldonk** [comment]
This issue is resolved in the latest 1.0.4 release.
