### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by RaphaelK12** [kareldonk/WMFPreview#3]
I could not find these files:
"WMFPreview_i.h"
"dlldata.c"
"WMFPreview_p.c ""
What are or contain these files? I didn't find it in the folder but some files have #include" WMFPreview_p.c "

**Comment by kareldonk** [comment]
Those files are generated when you use Visual Studio to open the [solution file](https://github.com/kareldonk/WMFPreview/blob/master/WMFPreview.sln) and build the project.
This is from the [readme](https://github.com/kareldonk/WMFPreview/blob/master/WMFPreview/ReadMe.txt):

> WMFPreview.idl
>     This file contains the IDL definitions of the type library, the interfaces
>     and co-classes defined in your project.
>     This file will be processed by the MIDL compiler to generate:
>         C++ interface definitions and GUID declarations (WMFPreview.h)
>         GUID definitions                                (WMFPreview_i.c)
>         A type library                                  (WMFPreview.tlb)
>         Marshaling code                                 (WMFPreview_p.c and dlldata.c)

**Comment by RaphaelK12** [comment]
Thanks a lot, I'm trying to learn about windows shell preview handle, I've found some other projects, but they used a lot of external libraries, this was the first one I found so far that doesn't make use of other libraries like IUP, IM, WX and others.
To start learning I will write one for viewing .TGA files and then for .OBJ files.
I've been researching how the preview handle works for a few days, but I haven't found anything that explains how it works.
Only .vdproj files are not working as I am using VS 2019, but this is not a problem.
Thanks.

**Comment by kareldonk** [comment]
No problem. If you have questions let me know. Most of the important code for thumbnail drawing is in the [WMFPreviewDoc.cpp](https://github.com/kareldonk/WMFPreview/blob/master/WMFPreview/WMFPreviewDoc.cpp) file. It shouldn't be too difficult to write one for TGA files. Microsoft also has some sample code for shell extensions on MSDN. 
The `.vdproj` files require that you install the [installer extension for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects).
